package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF005EA4)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF0077CE)
val OnPrimaryContainer = Color(0xFFFDFCFF)
val PrimaryFixed = Color(0xFFD3E4FF)
val PrimaryFixedDim = Color(0xFFA2C9FF)
val OnPrimaryFixed = Color(0xFF001C38)
val OnPrimaryFixedVariant = Color(0xFF004881)

val Secondary = Color(0xFF006398)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFF6CBDFE)
val OnSecondaryContainer = Color(0xFF004B75)
val SecondaryFixed = Color(0xFFCDE5FF)
val SecondaryFixedDim = Color(0xFF94CCFF)
val OnSecondaryFixed = Color(0xFF001D32)
val OnSecondaryFixedVariant = Color(0xFF004B74)

val Tertiary = Color(0xFF3E6078)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF577892)
val OnTertiaryContainer = Color(0xFFFCFCFF)
val TertiaryFixed = Color(0xFFC9E6FF)
val TertiaryFixedDim = Color(0xFFA8CBE7)
val OnTertiaryFixed = Color(0xFF001E2F)
val OnTertiaryFixedVariant = Color(0xFF274A62)

val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)

val Background = Color(0xFFF8F9FB)
val OnBackground = Color(0xFF191C1E)
val Surface = Color(0xFFF8F9FB)
val OnSurface = Color(0xFF191C1E)
val SurfaceVariant = Color(0xFFE0E3E5)
val OnSurfaceVariant = Color(0xFF404752)
val SurfaceDim = Color(0xFFD8DADC)
val SurfaceBright = Color(0xFFF8F9FB)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF2F4F6)
val SurfaceContainer = Color(0xFFECEEF0)
val SurfaceContainerHigh = Color(0xFFE6E8EA)
val SurfaceContainerHighest = Color(0xFFE0E3E5)
val InverseSurface = Color(0xFF2D3133)
val InverseOnSurface = Color(0xFFEFF1F3)
val InversePrimary = Color(0xFFA2C9FF)
val Outline = Color(0xFF707783)
val OutlineVariant = Color(0xFFC0C7D4)
val SurfaceTint = Color(0xFF0060A8)
